import { type NextPage } from "next";
import Head from "next/head";
import { useState } from 'react';

import { api } from "@/utils/api";

const Home: NextPage = () => {
  const [currentQuestionIndex, setQuestionIndex] = useState(0);
  const { data: questions } = api.quiz.questions.useQuery();

  const handleNextQuestion = () => {
    if (currentQuestionIndex >= 0 && currentQuestionIndex < 127) {
      setQuestionIndex(currentQuestionIndex + 1);
    }
  }

  const handlePrevQuestion = () => {
    if (currentQuestionIndex > 0 && currentQuestionIndex <= 127) {
      setQuestionIndex(currentQuestionIndex - 1);
    }
  }

  const handleRandomQuestion = () => {
    if (questions?.length) {
      const randomNumber = Math.floor(Math.random() * questions.length - 1);

      setQuestionIndex(randomNumber)
    }
  }

  const question = questions?.[currentQuestionIndex];
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto">
        <div className="flex gap-2 my-2 p-4">
          <button className="button-info" onClick={handlePrevQuestion}>Prev</button>
          <button className="button-info" onClick={handleNextQuestion}>Next</button>
          <button className="button-info" onClick={handleRandomQuestion}>Random</button>
        </div>
        <div className="flashcard flex flex-col gap-2">
          {question &&
            <>
              <h2 className="text-lg font-bold">{question?.question}</h2>
              {question?.answers.map(ans => <li key={ans}>{ans}</li>)}
            </>
          }
        </div>
      </main>
    </>
  );
};

export default Home;
