import { type NextPage } from "next";
import Head from "next/head";
import {useState} from 'react';

import { api } from "@/utils/api";

const Home: NextPage = () => {
  const [currentQuestionIndex, setQuestionIndex] = useState(0);
  const { data } = api.quiz.question.useQuery({ questionNumber: currentQuestionIndex });

  const handleNextQuestion = () => {
    if(currentQuestionIndex >= 0 && currentQuestionIndex < 127){
      setQuestionIndex(currentQuestionIndex + 1);
    }
  }

  const handlePrevQuestion = () => {
    if(currentQuestionIndex > 0 && currentQuestionIndex <= 127){
      setQuestionIndex(currentQuestionIndex - 1);
    }
  }

  const handleRandomQuestion = () => {
    const randomNumber = Math.floor(Math.random() * 127);

    setQuestionIndex(randomNumber)
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto">
        <div className="flex gap-2 my-2">
          <button className="button-info" onClick={handlePrevQuestion}>Prev</button>
          <button className="button-info" onClick={handleNextQuestion}>Next</button>
          <button className="button-info" onClick={handleRandomQuestion}>Random</button>
        </div>
        <div className="flashcard flex flex-col gap-2">
          <h2 className="text-lg font-bold">{data?.question?.question}</h2>
          {data?.question?.answers.map(ans => <li key={ans}>{ans}</li>)}
        </div>
      </main>
    </>
  );
};

export default Home;
